Flavio dev
CTU-IIG/kcf pull request #49
Opened 2019-08-13 08:00 UTC by FlavioK

CUDA Traditional memory

- Struct is now passed to memorymanager
- Use memory manager with all versions
    - This simplifies macro handling if traditional CUDA memory operations are taken into account
- MemLoc currLoc is mutable to allow modifications from const memberfunctions
- Overwriting ptr member functions in MatDynMem
    - This will be needed for debug output in next commit
- Removed some explicit copy operations since its now done in ptr functions
- Added build configuration

Changed debug output to copy data to host first

2019-08-13 13:44 UTC, wentasah commented
Can you please rebase it to master? I fixed travis configuration there.

2019-08-13 14:51 UTC, wentasah requested changes
Update a commit message a bit, explain what do you understand by traditional memory.

2019-08-13 14:51 UTC, wentasah commented on src/CMakeLists.txt
> +IF(CUDA_TRAD)
I'd prefer this to be called USE_CUDA_MEMCPY

2019-08-13 14:51 UTC, wentasah commented on src/dynmem.hpp
> +    std::map<size_t, std::stack<T> > map;
Use `std::stack<MemNode<T>>`

2019-08-13 14:51 UTC, wentasah commented on src/dynmem.hpp
> +    bool get(T *node, size_t size) {
Replace * with & (reference)

2019-08-13 14:51 UTC, wentasah commented on src/dynmem.hpp
> +    void put(T *node, size_t size) {
dtto

2019-08-13 14:51 UTC, wentasah commented on src/dynmem.hpp
> +        if (!mmng.get(reinterpret_cast<struct MemNode<void>*>(&mem), num_elem))
Add a new private methods `allocMem` and call it here. There will be three version of this method based on the #ifdefs.

2019-08-13 14:51 UTC, wentasah commented on src/dynmem.hpp
> +  mutable MemLoc currLoc;
I'd prefed having owner in both type and member name.

2019-08-13 14:51 UTC, wentasah commented on src/dynmem.hpp
> +#ifdef CUDA_TRAD
How often is that called? If often, we might want to speed it up by copying only CPU or GPU memory based on the current owner.

2019-08-13 14:51 UTC, wentasah commented on src/dynmem.hpp
>      {
Add assert for non-NULL pointers. (Needed due to move constructor)

2019-08-13 14:51 UTC, wentasah commented on src/dynmem.hpp
> +        toHost();
Better name would be copyToHost

2019-08-13 14:51 UTC, wentasah commented on src/dynmem.hpp
> +#ifdef CUDA_TRAD
Do not have ifdef here. Just make toHost empty function #if CUDA_TRAD.

2019-08-13 14:51 UTC, wentasah commented on src/dynmem.hpp
> +        memcpy(mem.ptr_h, rhs.mem.ptr_h, num_elem * sizeof(T));
Perhaps also add if (owner == ...)

2019-08-13 14:51 UTC, wentasah commented on src/dynmem.hpp
> +            CudaSafeCall(cudaMemcpyAsync(mem.ptr_h, mem.ptr_d, num_elem * sizeof(T), cudaMemcpyDeviceToHost));
This should be synchronous. Maybe, you also need cudaStreamSynchronize.

Also add `STREAM_PER_THREAD`.

2019-08-13 14:51 UTC, wentasah commented on src/dynmem.hpp
Add comment where are these used.

2021-09-28 06:21 UTC, FlavioK commented
I close this pull-request since its not needed anymore. I hope this is ok. :-)

2021-09-28 06:21 UTC, closed without merging

2021-10-21 14:44 UTC, wentasah commented
Sure it is OK :-)